version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres:postgrespassword@postgres:5432
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
